#!/bin/sh
'''exec' "/Users/nadiasasti/Documents/Tugas Pak Zikri/harga mobil/sklearn_env/bin/python3.11" "$0" "$@"
' '''
import sys
from streamlit.web.cli import main
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
